name: Daily Integration Check

on:
  schedule:
  - cron: "0 14 * * *"  # Daily at 14:00 UTC
  workflow_dispatch:  # so that we can also run manually, e.g. for testing


jobs:
  daily-integration-check:
    name: Pytest integration check
    env:
      SUPERSTAQ_API_KEY : ${{ secrets.SUPERSTAQ_API_KEY }}
      TEST_USER_IBMQ_TOKEN : ${{ secrets.TEST_USER_IBMQ_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./general-superstaq[dev] ./qiskit-superstaq[dev] ./cirq-superstaq[dev]
      - name: Pytest integration check
        run: |
          check/pytest_.py --integration
      - name: Create issue if integration check failed
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/integration-check-failure-issue.md
          update_existing: true

  load-testing-check:
    name: Load testing check
    env:
      SUPERSTAQ_API_KEY: ${{ secrets.SUPERSTAQ_API_KEY }}
      TEST_USER_IBMQ_TOKEN: ${{ secrets.TEST_USER_IBMQ_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./general-superstaq[dev] -e ./cirq-superstaq -e ./qiskit-superstaq -e ./supermarq-benchmarks
      - name: Load test
        run: |
          locust --config dev_tools/locust.conf -f dev_tools/locustfile.py --headless -u 10 -r 1 --run-time 1m
          
